server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pokemon-service
          uri: lb://pokemon-service
          predicates: 
            - Path= /api/v1/pokemon/**
          filters:
           - AuthenticationFilter
        - id: review-service
          uri: lb://review-service
          predicates: 
            - Path= /api/v1/review/**
          filters:
           - AuthenticationFilter  
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/auth/** 