server: 
    port: 8081
spring:
    cloud: 
        config:
            server:
                git:
                    default-label: circuit-breaker
                    uri: https://github.com/Pablo-mandalorian/Pokemon-Microservices
                    search-paths: config-data
    application: 
        name: config-server


